// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

console.log(/* array */[
      1,
      2,
      3
    ]);

console.log(/* :: */[
      1,
      /* :: */[
        2,
        /* :: */[
          3,
          /* [] */0
        ]
      ]
    ]);

console.log(/* :: */[
      1,
      /* :: */[
        2,
        /* :: */[
          3,
          /* [] */0
        ]
      ]
    ] === /* :: */[
      1,
      /* :: */[
        2,
        /* :: */[
          3,
          /* [] */0
        ]
      ]
    ]);

console.log(Caml_obj.caml_equal(/* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              3,
              /* [] */0
            ]
          ]
        ], /* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              3,
              /* [] */0
            ]
          ]
        ]));

var newScore = 20;

console.log("Enjoying the docs so far?");

var message = "hello world";

console.log(message);

var greeting = "Hello";

var score = 10;

var bool = true;

exports.greeting = greeting;
exports.score = score;
exports.newScore = newScore;
exports.bool = bool;
exports.message = message;
/*  Not a pure module */
