// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

var oneSlash = "\\";

console.log(oneSlash);

var greetingAndOneSlash = "Hello\nWorld\n\\\nHehe...\n";

console.log(greetingAndOneSlash);

var world = "世界";

var helloWorld = "你好, " + (String(world) + "");

console.log(helloWorld);

function isVowel(theChart) {
  if (theChart !== 97) {
    return theChart === 101;
  } else {
    return true;
  }
}

$$String.make(1, /* "a" */97);

var greeting = "Hello world!";

var multilineGreeting = "Hello\n  world!";

var c = /* "c" */99;

var greetings = "Hello world!";

var firstLetterOfAlphabet = /* "a" */97;

exports.greeting = greeting;
exports.multilineGreeting = multilineGreeting;
exports.c = c;
exports.oneSlash = oneSlash;
exports.greetings = greetings;
exports.greetingAndOneSlash = greetingAndOneSlash;
exports.world = world;
exports.helloWorld = helloWorld;
exports.firstLetterOfAlphabet = firstLetterOfAlphabet;
exports.isVowel = isVowel;
/*  Not a pure module */
