// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function add(x, y) {
  return x + y | 0;
}

var score = 10;

var myInt = 9;

var x = 10;

exports.score = score;
exports.myInt = myInt;
exports.add = add;
exports.x = x;
/* No side effect */
